accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import signup


urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
]

receipts/urls.py
from django.urls import path
from receipts.views import (
    ReceiptListView,
    AccountCreateView,
    AccountListView,
    ExpenseCategoryCreateView,
    ExpenseCategoryListView,
    ReceiptCreateView,
)


urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path(
        "accounts/create/", AccountCreateView.as_view(), name="create_accounts"
    ),
    path("accounts/", AccountListView.as_view(), name="account_list"),
    path(
        "categories/create/",
        ExpenseCategoryCreateView.as_view(),
        name="expenses_create",
    ),
    path(
        "categories/", ExpenseCategoryListView.as_view(), name="expenses_list"
    ),
    path("create/", ReceiptCreateView.as_view(), name="create_receipt"),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings

# Create your models here.

USER_MODEL = settings.AUTH_USER_MODEL


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="categories",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return str(self.name)


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)

    owner = models.ForeignKey(
        USER_MODEL,
        related_name="accounts",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return str(self.name)


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        USER_MODEL,
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        "ExpenseCategory", related_name="receipts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        "Account", null=True, related_name="receipts", on_delete=models.CASCADE
    )

    def __str__(self):
        return str(self.vendor)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


# Create your views here.

# function signup(request)
#     if the request method is "POST", then
#         form = UserCreationForm(request.POST)
#         if the form is valid, then
#             username = the "username" value from the request.POST dictionary
#             password = the "password1" value from the request.POST dictionary
#             user = create a new user using username and password
#             save the user object
#             login the user with the request and user object
#             return a redirect to the "home" path
#     otherwise,
#         form = UserCreationForm(request.POST)
#     context = dictionary with key "form" and value form
#     return render with request, "registration/signup.html", and the context


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm(request.POST)
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

receipts/views.py
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView

from receipts.models import ExpenseCategory, Receipt, Account

# Create your views here.


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    #  display the data in tables. Make sure that you filter the data
    # for only the current user. You can do this by creating your own
    # get_queryset method on the views and using the general form:
    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


## to access an create view a person must be logged in
# create acounts/create for a view to create a new receipt account


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "accounts/create.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("account_list")

    # return redirect("") should redirect to account list view?? from path


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "accounts/list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


# create a categories/creates for a view to create a new expense


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "categories/create.html"
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("expenses_list")


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "categories/list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


# create a create/ for the view to create a new receipts


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/create.html"
    fields = [
        "vendor",
        "total",
        "tax",
        "date",
        "category",
        "account",
    ]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")

receipts/templates/accounts/create.html
{% extends 'base.html' %}
{% comment %} <p> This is the accounts create</p> {% endcomment %}

{% block content %}

<div>
    <h1> Creating an account within Receipts</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Create</button>
    </form>
</div>

{% endblock content %}

receipts/templates/accounts/list.html
{% extends 'base.html' %}

{% comment %} <p> this is accounts list</p> {% endcomment %}

{% block content %}
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Number</th>
            <th>Number of receipts</th>
        </tr>
    </thead>
    <tbody>
        {% for waterbottle in account_list %}
        <tr>
            <td>{{ waterbottle.name }}</td>
            <td>{{ waterbottle.number }}</td>
            <td>{{ waterbottle.receipts.all|length }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

receipts/templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <title>MY RECEIPTS!</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'home' %}">Receipts</a>
                    </li>
                    <li>
                        <a href="{% url 'create_accounts' %}">Create Account</a>
                    </li>
                    <li>
                        <a href="{% url 'account_list' %}">Accounts</a>
                    </li>
                    <li>
                        <a href="{% url 'expenses_create' %}">Create an Expense</a>
                    </li>
                    <li>
                        <a href="{% url 'expenses_list' %}">Expenses</a>
                    </li>
                    <li>
                        <a href="{% url 'create_receipt' %}">Create a Receipt</a>
                    </li>
                    <li>
                        <a href="{% url 'logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{% url 'signup' %}">Sign Up</a>
                    </li>
                    <li>
                        <a href="{% url 'login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
    <main>
        {% block content %}
        {% endblock content %}
    </main>
    </body>
</html>

receipts/templates/categories/create.html
{% extends 'base.html' %}
{% comment %} this is the expenses create {% endcomment %}

{% block content %}
    <div>
        <h1>Creating an Expense Category</h1>
        <form method ="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button> Create</button>
        </form>
    </div>
{% endblock content %}

receipts/templates/categories/list.html
{% extends 'base.html' %}

{% comment %} this is expenses' list {% endcomment %}

{% block content %}
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Number of receipts</th>
        </tr>
    </thead>
    <tbody>
        {% for banana in expensecategory_list %}
        <tr>
            <td>{{ banana.name }}</td>
            <td>{{ banana.receipts.all|length }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

receipts/templates/receipts/create.html
{% extends 'base.html' %}
{% comment %} <p> this is the receipt create</p> {% endcomment %}

{% block content %}
    <div>
        <h1>Creating an Receipt</h1>
        <form method ="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button> Create</button>
        </form>
    </div>
{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %}
{% block content %}
<table>
    <thead>
        <tr>
            <td>Vendor</td>
            <td>Total</td>
            <td>Tax</td>
            <td>Date</td>
            <td>Category</td>
            <td>Account</td>
        </tr>
    </thead>
    <tbody>
        {% for receipt in receipt_list %}
        <tr>
            <td>{{ receipt.vendor }}</td>
            <td>{{ receipt.total }}</td>
            <td>{{ receipt.tax }}</td>
            <td>{{ receipt.date }}</td>
            <td>{{ receipt.category.name }}</td>
            {%  if receipt.account.name == None %}
                <td>Cash</td>
            {% else %}
            <td>{{ receipt.account.name }}</td>
                {% comment %} If account is None, then output "Cash" instead of none {% endcomment %}
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}